/**
 * Comprehensive Practice Question Bank Generation & Regeneration Engine
 * Guarantees at least 50 high-yield, unique questions per generation/regeneration across 5 balanced categories.
 */

// Helper to normalize strings for duplicate detection
function normalizeQ(text) {
  if (!text || typeof text !== "string") return "";
  return text
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

function isDuplicate(qText, exclusionList) {
  if (!qText || !Array.isArray(exclusionList) || exclusionList.length === 0) return false;
  const cleanQ = normalizeQ(qText);
  if (!cleanQ) return false;

  return exclusionList.some((item) => {
    const cleanItem = normalizeQ(typeof item === "string" ? item : item?.question);
    if (!cleanItem) return false;
    if (cleanItem === cleanQ) return true;
    if (cleanItem.length > 35 && cleanQ.length > 35) {
      if (cleanItem.includes(cleanQ) || cleanQ.includes(cleanItem)) return true;
    }
    return false;
  });
}

// =========================================================================
// 1. COMPREHENSIVE DOMAIN PROCEDURAL QUESTION DATA (50+ Per Discipline Tier)
// =========================================================================
const DOMAIN_QUESTION_POOLS = {
  mechanical: {
    technical: [
      { q: "What are the fundamental differences between 2D drafting in AutoCAD and 3D parametric feature-based modeling in SolidWorks or CATIA?", diff: "Basic", concepts: ["Parametric Modeling", "2D Blueprints vs 3D Solids", "Associativity"], ans: "Parametric CAD maintains parent-child feature relationships, enables automatic 2D drawing updates on 3D geometry changes, and captures design intent through dimensional constraints." },
      { q: "Explain the Stress-Strain curve for structural mild steel. What is the significance of the Yield Point, Ultimate Tensile Strength (UTS), and Elastic Modulus?", diff: "Basic", concepts: ["Stress-Strain Curve", "Yield Strength", "Hooke's Law", "Plastic Deformation"], ans: "Hooke's Law defines the linear elastic region up to the proportional limit. The yield point marks permanent plastic deformation, UTS is maximum load capacity, and slope equals Young's modulus." },
      { q: "What is the difference between ductile and brittle materials under tensile loading? How do their fracture surfaces differ?", diff: "Basic", concepts: ["Ductility", "Brittleness", "Cup-and-Cone Fracture", "Cleavage"], ans: "Ductile materials undergo extensive plastic deformation before failing with a cup-and-cone shear fracture, whereas brittle materials fail abruptly with flat cleavage planes normal to maximum tensile stress." },
      { q: "Explain Pascal's Principle and how it forms the operating foundation for industrial hydraulic actuator systems.", diff: "Basic", concepts: ["Pascal's Law", "Hydraulic Pressure", "Force Multiplication", "Incompressibility"], ans: "Pressure applied to an enclosed incompressibile fluid is transmitted undiminished in all directions (F1/A1 = F2/A2), enabling force amplification proportional to cylinder piston area." },
      { q: "What are the core mechanical differences between Spur, Helical, Bevel, and Worm gears in power transmission?", diff: "Basic", concepts: ["Gear Types", "Axial Thrust", "Contact Ratio", "Speed Reduction"], ans: "Spur gears transmit power between parallel shafts with simple manufacturing; Helical gears offer gradual tooth engagement and higher contact ratios but produce axial thrust; Bevel gears connect intersecting shafts; Worm gears offer high single-stage reduction ratios with non-backdrivable locking." },
      { q: "What is the difference between conduction, convection, and radiation heat transfer modes in thermodynamic systems?", diff: "Basic", concepts: ["Fourier's Law", "Newton's Law of Cooling", "Stefan-Boltzmann Law"], ans: "Conduction occurs via microscopic molecular collisions in solids (Fourier's law); Convection involves bulk fluid motion across surfaces (Newton's cooling law); Radiation transfers electromagnetic energy without requiring a medium (Stefan-Boltzmann law)." },
      { q: "What is Geometric Dimensioning & Tolerancing (GD&T)? Explain the difference between Coordinate Tolerancing and True Position under Maximum Material Condition (MMC).", diff: "Intermediate", concepts: ["ASME Y14.5 GD&T", "True Position", "Datum Reference Frame", "Bonus Tolerance (MMC)"], ans: "True Position defines a cylindrical 3D tolerance zone that provides 57% more usable tolerance area than square coordinate tolerances and allows bonus tolerance as the feature departs from MMC." },
      { q: "Explain the Von Mises yield criterion. Why is it preferred over Maximum Principal Stress (Rankine) when evaluating multi-axial stress in ductile materials in FEA?", diff: "Intermediate", concepts: ["Distortion Energy Theory", "Von Mises Stress", "Ductile Failure", "FEA Stress Tensors"], ans: "Von Mises is based on shear distortion energy and accurately predicts ductile yielding under combined tension, compression, and shear states, unlike Rankine which only considers maximum normal stress." },
      { q: "What Design for Manufacturing (DFM) and Design for Assembly (DFA) rules do you follow when designing parts for Injection Molding versus CNC Milling?", diff: "Intermediate", concepts: ["DFM / DFA", "Draft Angles", "Uniform Wall Thickness", "CNC Tool Access & Fillets"], ans: "For injection molding: maintain uniform wall thickness (to avoid sink marks), 1-2 degree draft angles, and rib coring. For CNC milling: standard internal corner radii matching tool diameters, minimize deep pockets (>4x tool diameter), and avoid multi-axis re-fixturing." },
      { q: "How do you perform a tolerance stack-up analysis using Worst-Case versus Root-Sum-Square (RSS) statistical methods?", diff: "Intermediate", concepts: ["Tolerance Stack-Up", "Worst-Case Analysis", "RSS Statistical Tolerancing", "Clearance Limits"], ans: "Worst-Case linearly adds maximum limits (conservative for critical safety seals), while RSS assumes normal independent distributions and squares individual tolerances, reducing manufacturing costs for high-volume assemblies." },
      { q: "What mechanical factors dictate the selection between ball bearings, roller bearings, and hydrodynamic journal bearings?", diff: "Intermediate", concepts: ["Bearing Selection", "Radial vs Thrust Load", "L10 Bearing Life", "Sommerfeld Number"], ans: "Ball bearings handle high-speed moderate radial/thrust loads; Roller bearings handle heavy shock and radial loads; Hydrodynamic journal bearings operate with zero metal contact for extreme-speed turbine shafts under continuous oil film pressure." },
      { q: "Explain the metallurgical purpose and mechanical implementation of heat treatment processes (Annealing, Quenching, and Tempering) for medium carbon steel.", diff: "Intermediate", concepts: ["Austenite / Martensite Transformation", "Quenching & Tempering", "Hardness vs Toughness"], ans: "Annealing softens steel by furnace cooling to relieve internal stress. Quenching rapidly cools from austenitizing temperature to form hard, brittle martensite. Tempering reheats below critical point to restore ductility and toughness." },
      { q: "How do you design a mechanical coil compression spring for a given load, deflection, and fatigue life constraint?", diff: "Intermediate", concepts: ["Spring Index (C)", "Wahl Curvature Correction Factor", "Torsional Shear Stress", "Spring Rate (k)"], ans: "Calculate spring rate k = Gd^4 / (8D^3N), determine active coils, compute torsional stress with Wahl curvature correction factor, and ensure operational stress remains below torsional endurance limit." },
      { q: "Detail an advanced optimization framework for high-temperature creep deformation and Larson-Miller parameter in turbine blades.", diff: "Advanced", concepts: ["Creep Rupture", "Larson-Miller Parameter", "Grain Boundary Sliding", "Single-Crystal Superalloys"], ans: "Model primary, secondary (steady-state rate), and tertiary creep. Apply Larson-Miller parameter LMP = T(C + log t_r) to extrapolate life, and specify single-crystal nickel superalloys with directional solidification." },
      { q: "In Finite Element Analysis (FEA), how do you identify and mitigate artificial stress singularities versus true physical stress concentrations?", diff: "Advanced", concepts: ["h-refinement vs p-refinement", "Stress Singularities", "Mesh Convergence", "Re-entrant Corners"], ans: "Singularities exhibit non-converging stress that increases infinitely with mesh refinement at sharp re-entrant corners or point loads. Resolve by modeling true fillet radii and applying distributed traction loads." },
      { q: "How do you analyze high-cycle fatigue (HCF) using S-N curves, Goodman mean stress correction, and Miner's Rule for cumulative damage?", diff: "Advanced", concepts: ["Goodman Diagram", "S-N Endurance Limit", "Miner's Cumulative Damage Rule", "Surface Finish Factor"], ans: "Compute alternating and mean stresses, apply Modified Goodman relation (Sa/Se + Sm/Sut = 1), scale endurance limit Se by Marin factors (surface, size, temperature), and compute damage sum D = sum(n_i / N_i) <= 1." },
      { q: "Explain the kinematics and dynamics of planetary (epicyclic) gear trains using the tabular method and Willis formula.", diff: "Advanced", concepts: ["Planetary Gear Trains", "Sun, Planet, Carrier, Ring", "Torque Ratio", "Willis Formula"], ans: "Fix the carrier, compute gear ratios between sun and ring gears relative to carrier (omega_sun - omega_carrier)/(omega_ring - omega_carrier) = -N_ring/N_sun, and superimpose carrier rotational velocity." },
      { q: "How do you design and balance high-speed rotating shafts to prevent resonant critical speed whirling?", diff: "Advanced", concepts: ["Critical Speed", "Rotor Dynamics", "Jeffcott Rotor Model", "Dynamic Balancing (ISO 1940)"], ans: "Calculate first natural bending frequency using Rayleigh-Ritz method, ensure operating speed is +/-20% away from critical speed, and apply two-plane dynamic balancing to reduce unbalance eccentricity." },
    ],
    problemSolving: [
      { q: "A newly designed centrifugal pump assembly vibrates excessively above 3,000 RPM. Walk through your step-by-step troubleshooting protocol.", diff: "Intermediate", concepts: ["Vibration FFT Analysis", "Cavitation", "Shaft Misalignment", "Resonance"], ans: "1. Capture vibration spectrum via accelerometer to check 1X (unbalance), 2X (misalignment), or vane-pass frequency. 2. Verify dynamic balancing. 3. Check suction NPSHa vs NPSHr for cavitation. 4. Run bump test to verify natural resonance." },
      { q: "An injection molded plastic enclosure is warping along its 200mm side. How do you diagnose the root cause and modify the mold tooling?", diff: "Intermediate", concepts: ["Differential Shrinkage", "Cooling Channel Balance", "Rib Design", "Gate Placement"], ans: "Diagnose differential cooling rates and volumetric shrinkage. Adjust mold cooling channel flow, reduce rib thickness to 50-60% of nominal wall thickness, and relocate injection gates to ensure uniform mold packing pressure." },
      { q: "A bolted flanged connection on a high-pressure steam line is leaking during thermal cycling. How do you redesign the joint?", diff: "Advanced", concepts: ["Bolt Preload Relaxation", "Thermal Expansion Mismatch", "Spiral Wound Gasket", "Flange Rigidity"], ans: "Calculate differential thermal expansion between bolts and flange. Switch to high-temperature alloy studs (B7/B16), use spiral-wound graphite-filled gaskets, and apply controlled torque-angle tightening with disc spring Belleville washers." },
      { q: "Design a mechanical lifting scissor mechanism capable of raising a 1,500 kg payload by 1.2 meters. Detail actuator force sizing.", diff: "Advanced", concepts: ["Scissor Geometry", "Linkage Kinematics", "Hydraulic Cylinder Sizing", "Buckling Safety Factor"], ans: "Compute required hydraulic thrust at lowest retracted angle where mechanical advantage is minimum (F = W / (2*tan(theta))). Check scissor arms for Euler column buckling and pin joints for bearing shear stress." },
      { q: "A gearbox prototype exhibits premature pitting fatigue on drive pinion teeth after only 200 hours of operation. What is your diagnosis?", diff: "Advanced", concepts: ["Contact Stress (Hertzian)", "Lubrication Breakdown", "Case Hardening Depth", "AGMA Pitting Resistance"], ans: "Excessive Hertzian contact stress or insufficient elastohydrodynamic oil film thickness (lambda < 1). Increase oil viscosity, verify AGMA contact stress limits, increase tooth face width, and verify carburized case depth." },
      { q: "A sheet metal bracket is cracking at the 90-degree bend radius during progressive stamping. How do you solve this?", diff: "Intermediate", concepts: ["Bend Radius vs Sheet Thickness", "Grain Direction", "Springback", "Relief Notches"], ans: "Ensure inner bend radius >= 1x material thickness (or 2x for high-strength alloys), orient bend line perpendicular to sheet rolling grain direction, and introduce bend relief notches at edges." },
      { q: "How would you design a heat sink with forced convection cooling for a 250W power electronics inverter module?", diff: "Intermediate", concepts: ["Thermal Resistance Network", "Fin Efficiency", "Pressure Drop vs Flow Rate", "TIM Selection"], ans: "Construct 1D thermal resistance chain (R_jc + R_cs + R_sa <= (T_j_max - T_ambient)/Power). Optimize fin pitch, height, and thickness to balance convection heat transfer coefficient against fan static pressure drop." },
      { q: "A CNC machined aluminum aerospace fitting failed in fatigue testing at a sharp internal fillet. How do you redesign it?", diff: "Intermediate", concepts: ["Stress Concentration Factor (Kt)", "Fillet Optimization", "Shot Peening", "Surface Roughness"], ans: "Increase internal corner radius to reduce Kt from Peterson charts, specify CNC ball-end milling finish (Ra < 0.8 um), and introduce compressive surface residual stresses via shot peening." },
      { q: "Design an automated conveyor transfer mechanism that re-orients cylindrical parts 90 degrees at a rate of 120 parts per minute.", diff: "Intermediate", concepts: ["Pneumatic / Cam Actuation", "Timing Diagrams", "Inertia Calculation", "Guide Rails"], ans: "Evaluate barrel cam or pneumatic rotary gripper mechanism. Size motor torque for rapid angular acceleration (T = J*alpha), implement smooth S-curve acceleration profiles, and design adjustable urethane guide rails." },
      { q: "A robotic arm joint experiences significant backlash and positioning errors under rapid trajectory reversals. How do you eliminate backlash?", diff: "Advanced", concepts: ["Harmonic Drive", "Cycloidal Reducer", "Dual-Motor Preload", "Encoder Resolution"], ans: "Replace standard planetary gearing with zero-backlash strain wave (harmonic) or cycloidal reducers, implement secondary output shaft absolute encoders, or apply electronic dual-pinion torque bias preloading." },
      { q: "Analyze why a high-speed spindle motor is experiencing thermal expansion runout causing machining dimensional drift.", diff: "Advanced", concepts: ["Thermal Growth", "Bearing Preload Loss", "Liquid Cooling Jackets", "Shaft Expansion Compensation"], ans: "Internal frictional heat in angular contact bearings causes axial shaft growth. Implement closed-loop refrigerated spindle jacket cooling, ceramic hybrid ball bearings, and floating rear bearing expansion packs." },
      { q: "How do you design a progressive stamping die layout for high-volume manufacturing of a complex electrical terminal connector?", diff: "Advanced", concepts: ["Die Strip Layout", "Carrier Web Design", "Pilots & Pitch", "Punch / Die Clearances"], ans: "Design sequence: pierce pilot holes, notch profile, pre-form bends, final form, and cut-off. Maintain rigid carrier strip webs, ensure 5-8% cutting clearance per side, and integrate progressive die sensor monitoring." },
    ],
    behavioral: [
      { q: "Describe a complex mechanical engineering project where you had to balance aggressive deadlines against strict safety and quality standards.", diff: "Intermediate", concepts: ["STAR Method", "Prioritization", "Safety Integrity"], ans: "Detail the Situation, Task, Action (implementing risk matrices and critical path scheduling), and quantifiable Result demonstrating on-time completion with 100% test validation." },
      { q: "Tell me about a time you identified a critical flaw in a colleague's CAD model or engineering calculation before manufacturing.", diff: "Intermediate", concepts: ["Peer Review", "Constructive Feedback", "Quality Assurance"], ans: "Explain how you discovered the interference/stress error during peer review, walked through the data collaboratively without assigning blame, and updated the design collaboratively." },
      { q: "Describe a situation where a prototype failed during initial laboratory testing. How did you lead the team through root cause recovery?", diff: "Intermediate", concepts: ["Resilience", "Root Cause Analysis", "Action Plan"], ans: "Emphasize maintaining team focus, implementing 5-Why/Fishbone containment, isolating failure modes, executing design modifications, and passing secondary qualification." },
      { q: "How do you handle conflicting design priorities between mechanical engineering, electrical hardware, and industrial design aesthetics?", diff: "Intermediate", concepts: ["Cross-Functional Alignment", "Trade-Off Matrix", "Communication"], ans: "Use objective trade-off matrices evaluating thermal, structural, and tooling constraints against ergonomic and PCB envelope requirements to reach a data-driven consensus." },
      { q: "Give an example of a time you successfully persuaded manufacturing shop-floor technicians to adopt a new assembly process.", diff: "Intermediate", concepts: ["Stakeholder Buy-In", "Active Listening", "Change Management"], ans: "Walk through observing their pain points on the assembly line, building ergonomic prototype jigs with their direct input, and showing immediate cycle-time reductions." },
      { q: "Describe a situation where you had to make a high-stakes engineering design decision with incomplete experimental or simulation data.", diff: "Advanced", concepts: ["Risk Management", "Engineering Judgement", "Safety Factors"], ans: "Explain applying conservative analytical bounds, consulting senior subject matter experts, implementing incremental milestone validation, and building fail-safe redundancies." },
      { q: "Tell me about a time you took the initiative to optimize an existing engineering workflow or standard operating procedure (SOP).", diff: "Intermediate", concepts: ["Continuous Improvement", "Automation", "Efficiency"], ans: "Describe automating CAD drawing template generation, standardizing fastener hardware libraries, or scripting FEA batch runs to save engineering team hours." },
      { q: "How do you manage your engineering workload when multiple high-priority projects demand immediate CAD updates and fabrication support?", diff: "Intermediate", concepts: ["Time Management", "Critical Path", "Stakeholder Communication"], ans: "Prioritize based on critical path tooling release dates, communicate realistic timeline milestones transparently to project managers, and eliminate non-essential meetings." },
      { q: "Describe a time you received critical or harsh feedback on an engineering deliverable from a customer or chief engineer. How did you respond?", diff: "Intermediate", concepts: ["Coachability", "Professional Maturity", "Continuous Growth"], ans: "Explain actively listening without defensiveness, extracting technical merit, systematically revising the deliverable, and creating verification checklists to prevent recurrence." },
      { q: "Share an experience where you mentored a junior engineer or intern on CAD modeling standards and engineering design best practices.", diff: "Intermediate", concepts: ["Leadership", "Knowledge Transfer", "Mentorship"], ans: "Detail establishing regular 1-on-1 design reviews, teaching DFM fundamentals and parametric CAD hygiene, and helping them gain confidence in presenting to clients." },
    ],
    situational: [
      { q: "Scenario: A key supplier informs you 2 weeks before production launch that the specified alloy material is on a 6-month backorder. What do you do?", diff: "Intermediate", concepts: ["Material Substitution", "Equivalent Stress Check", "Supplier Management"], ans: "1. Identify equivalent alloy grades (e.g. 6061-T6 vs 6082-T6 or 4140 vs 4340). 2. Verify mechanical properties, machinability, and weldability. 3. Re-run FEA stress checks. 4. Authorize an emergency engineering change notice (ECN)." },
      { q: "Scenario: During assembly of a pre-production batch, workers report that 15% of parts are binding due to tight clearance tolerances. How do you resolve this?", diff: "Intermediate", concepts: ["Tolerance Investigation", "CMM Inspection", "Selective Assembly"], ans: "Halt line, perform Coordinate Measuring Machine (CMM) inspection on mating components to identify which part is out-of-spec, calculate actual clearance distribution, and implement selective assembly as temporary containment while adjusting tooling." },
      { q: "Scenario: Management requests that you reduce the safety factor of a structural bracket from 2.0 to 1.15 to cut unit weight and material costs. How do you respond?", diff: "Advanced", concepts: ["Ethics & Safety", "Risk Evaluation", "Alternative Optimization"], ans: "Hold firm on safety requirements. Present data showing risks of fatigue failure, shock load unpredictability, and regulatory liabilities. Offer structural topology optimization or high-strength material alternatives to achieve weight reduction safely." },
      { q: "Scenario: A high-precision CNC machine spindle suddenly crashes into a fixture during a routine job. What are your immediate actions?", diff: "Intermediate", concepts: ["Emergency Response", "Machine Alignment Check", "G-Code Verification"], ans: "1. Lockout/tagout machine and ensure operator safety. 2. Verify spindle runout, axis tramming, and linear rail geometry. 3. Audit CAM G-code toolpaths and coordinate work offset zeroes. 4. Implement dry-run verification protocols." },
      { q: "Scenario: A customer reports that your mechanical product is operating at 85 dBA, exceeding their 70 dBA contract specification. How do you handle this?", diff: "Intermediate", concepts: ["Acoustic Triage", "Noise Source Identification", "Vibration Damping"], ans: "Perform sound intensity mapping and octave band analysis to isolate noise sources (gear mesh, fan turbulence, bearing rattle). Implement acoustic insulation, dynamic damping mounts, and optimized fan blade profiles." },
      { q: "Scenario: You discover that a critical FEA simulation used wrong boundary constraints after 1,000 fabricated units have already been manufactured. What do you do?", diff: "Advanced", concepts: ["Integrity", "Immediate Containment", "Physical Proof Testing"], ans: "Immediately inform engineering leadership and quality management. Quarantine fabricated inventory. Pull units for physical proof-load and fatigue testing to evaluate true real-world safety margins, and rework or scrap based on empirical data." },
      { q: "Scenario: The environmental test chamber fails midway through a 500-hour thermal qualification test of a sealed mechanical enclosure. How do you proceed?", diff: "Intermediate", concepts: ["Test Integrity", "Data Logging Audit", "Chamber Recalibration"], ans: "Inspect test logs to determine exact temperature profile prior to failure. Inspect the test article for premature seal degradation. Authorize chamber repair, document the deviation formally, and re-start or append testing per MIL-STD/IEC guidelines." },
      { q: "Scenario: Two senior mechanical designers disagree fundamentally on whether to use a cast aluminum housing or a welded steel fabrication. How do you break the tie?", diff: "Intermediate", concepts: ["Decision Matrix", "CapEx vs OpEx", "Production Volume"], ans: "Build a quantitative decision matrix evaluating annual production volume (tooling amortization for casting vs recurring labor for welding), stiffness-to-weight ratio, sealing integrity, and delivery lead times." },
      { q: "Scenario: A client demands a major dimensional change to an injection molded component 3 days before final mold steel cutting begins. What is your process?", diff: "Intermediate", concepts: ["Change Order Impact", "Tooling Schedule", "Cost Estimation"], ans: "Assess CAD modifications, calculate mold tooling rework costs and delivery schedule delays, issue a formal Engineering Change Proposal (ECP) with cost/time trade-offs, and obtain written customer sign-off before proceeding." },
      { q: "Scenario: During physical drop testing, a handheld mechanical device's snap-fit latch consistently shears off on impact. What is your redesign strategy?", diff: "Intermediate", concepts: ["Snap-Fit Design", "Impact Energy Dissipation", "Radius Fillet / Resin"], ans: "Increase root fillet radius to eliminate notch stress concentrations, reduce deflection strain (elongation < 2-3%), modify latch taper angle, or evaluate high-impact polycarbonate/ABS resin blends." },
    ],
    roleSpecific: [
      { q: "What industry standards govern mechanical drafting, welding symbols, and pressure vessel design (e.g. ASME Y14.5, AWS D1.1, ASME Section VIII)?", diff: "Basic", concepts: ["ASME Y14.5", "AWS D1.1", "ASME Boiler & Pressure Vessel Code"], ans: "ASME Y14.5 standardizes GD&T; AWS D1.1 governs structural steel welding symbols and inspection; ASME Section VIII governs design, fabrication, and pressure testing of unfired pressure vessels." },
      { q: "How do you configure and interpret Finite Element Analysis (FEA) mesh quality metrics (Aspect Ratio, Jacobian, Skewness, Tet vs Hex elements)?", diff: "Intermediate", concepts: ["FEA Mesh Quality", "Jacobian Ratio", "Skewness", "Hexahedral Meshing"], ans: "Maintain Jacobian > 0.6, Aspect Ratio < 5, and low skewness. Use second-order hexahedral (brick) elements for bending/fatigue regions and high-density second-order tetrahedrals for complex organic geometries." },
      { q: "What are the core operating principles and selection criteria for industrial pneumatics (FRL units, directional solenoid valves, cylinder cushioning)?", diff: "Intermediate", concepts: ["Pneumatic FRL", "5/2 Solenoid Valves", "Adjustable Cushioning"], ans: "Filter-Regulator-Lubricator (FRL) prepares clean compressed air at stable pressure; 5-way 2-position valves control double-acting cylinders; adjustable pneumatic cushioning decelerates heavy moving payloads safely." },
      { q: "Explain the mechanical design principles and calculation methods for belt and chain drives (Center Distance, Wrap Angle, Tensioning).", diff: "Intermediate", concepts: ["Belt Wrap Angle", "Initial Tensioning", "Chain Sag", "Service Factor"], ans: "Ensure minimum wrap angle > 120 degrees on smaller pulley, apply service factors for shock loads, calculate slack-side vs tight-side tension (T1/T2 = e^(mu*theta)), and integrate adjustable idler tensioners." },
      { q: "How do you design a high-reliability O-ring elastomeric seal groove for static versus dynamic reciprocating piston applications per Parker O-Ring Handbook?", diff: "Intermediate", concepts: ["Parker O-Ring Standards", "Groove Squeeze & Fill", "Extrusion Gap", "Backup Rings"], ans: "For static seals: 20-30% squeeze with 65-80% gland fill. For dynamic reciprocating seals: 10-18% squeeze to minimize friction. Provide backup rings when pressure exceeds 10 MPa (1500 psi) to prevent gap extrusion." },
      { q: "What are the key differences and design considerations between additive manufacturing (DMLS/SLM) and subtractive 5-axis CNC machining?", diff: "Intermediate", concepts: ["Additive vs Subtractive", "Topology Optimization", "Build Orientation", "Post-Machining"], ans: "DMLS enables organic topology optimization, internal cooling channels, and lightweight lattice structures but requires support removal and post-machining; 5-axis CNC provides superior surface finish and tight tolerances." },
      { q: "How do you calculate thermal stress and required expansion loop sizing in long industrial piping systems per ASME B31.3?", diff: "Advanced", concepts: ["Thermal Piping Expansion", "ASME B31.3", "Expansion Loops", "Pipe Flexibility Analysis"], ans: "Calculate longitudinal thermal expansion delta_L = alpha * L * delta_T. Design U-shaped or Z-shaped expansion loops so that bending stress at pipe elbows remains within allowable displacement stress range Sa." },
      { q: "What factors dictate the selection of sheet metal forming presses (Mechanical Crank vs Hydraulic vs Servo presses)?", diff: "Advanced", concepts: ["Press Types", "Tonnage Curve", "Stroke Velocity", "Deep Drawing"], ans: "Mechanical crank presses offer high SPM for blanking/piercing; Hydraulic presses provide full rated tonnage throughout entire stroke for deep drawing; Servo presses allow programmable slide velocity and dwell time." },
      { q: "Explain the mechanical considerations in designing dynamic linkages with low inertia, high stiffness, and zero backlash for delta robots.", diff: "Advanced", concepts: ["Carbon Fiber Tubes", "Preloaded Ball Joints", "Direct Drive Motors", "Kinematic Bandwidth"], ans: "Utilize lightweight carbon fiber linkage arms with titanium end-fittings, preloaded zero-clearance spherical ball joints, and direct-drive torque motors to minimize settling time and maximize trajectory bandwidth." },
      { q: "How do you establish an automated inspection protocol using 3D Optical Laser Scanning / Structured Light and CMM probing for first-article inspection (FAI)?", diff: "Intermediate", concepts: ["Structured Light Scanning", "CAD Heatmap Comparison", "FAI AS9102", "CMM Probing"], ans: "Align scan point clouds to native CAD via datum reference alignment, generate full-field 3D color deviation heatmaps for form errors, and probe critical GD&T features on CMM to document AS9102 FAI compliance." },
    ],
  },

  cybersecurity: {
    technical: [
      { q: "What is the difference between Authentication, Authorization, and Accounting (AAA) in enterprise security architectures?", diff: "Basic", concepts: ["Authentication vs Authorization", "Accounting / Auditing", "RBAC / ABAC"], ans: "Authentication verifies identity (who you are); Authorization determines access rights and permissions (what you can do); Accounting logs and tracks user actions (what you did)." },
      { q: "Explain the components of the CIA Triad (Confidentiality, Integrity, Availability) and provide real-world defense mechanisms for each.", diff: "Basic", concepts: ["CIA Triad", "Encryption", "Hashing & Digital Signatures", "DDoS Mitigation & Redundancy"], ans: "Confidentiality ensures unauthorized users cannot read data (AES-256 encryption, TLS); Integrity guarantees data is not altered (SHA-256 hashes, HMAC); Availability ensures continuous system access (load balancing, DDoS defense)." },
      { q: "What are the differences between symmetric encryption (AES) and asymmetric encryption (RSA/ECC)? When do you use each?", diff: "Basic", concepts: ["Symmetric vs Asymmetric", "AES-GCM", "Public/Private Keys", "Hybrid Encryption"], ans: "Symmetric uses one shared key for high-speed bulk data encryption; Asymmetric uses public/private key pairs for key exchange and digital signatures. Modern protocols use hybrid encryption (asymmetric for handshake, symmetric for session data)." },
      { q: "What is the TCP 3-Way Handshake, and how does a SYN Flood DDoS attack exploit this mechanism?", diff: "Basic", concepts: ["SYN, SYN-ACK, ACK", "Half-Open Connections", "SYN Cookies", "Backlog Queue"], ans: "TCP handshake: Client sends SYN, Server replies SYN-ACK and reserves memory in connection backlog, Client sends ACK. In SYN flood, attacker sends thousands of spoofed SYNs and never sends ACK, exhausting server connection memory." },
      { q: "What is the difference between a Network Firewall, a Web Application Firewall (WAF), and an Intrusion Detection/Prevention System (IDS/IPS)?", diff: "Basic", concepts: ["L3/L4 Firewall", "L7 WAF", "Signature vs Anomaly IDS/IPS"], ans: "Network firewalls filter Layer 3/4 packet headers (IP/Port); WAFs inspect Layer 7 HTTP payloads against OWASP Top 10 (SQLi, XSS); IDS/IPS monitors full network traffic streams for malicious signatures and anomalous patterns." },
      { q: "Explain the principle of Least Privilege and how it mitigates privilege escalation and lateral movement.", diff: "Basic", concepts: ["Least Privilege", "Role-Based Access Control (RBAC)", "Zero Standing Privileges (ZSP)"], ans: "Users and services are granted only the minimum permissions necessary to complete their job, preventing compromised low-level accounts from accessing sensitive databases or pivoting across the network." },
      { q: "How does a Cross-Site Scripting (XSS) attack work? Contrast Stored, Reflected, and DOM-based XSS with remediation strategies.", diff: "Intermediate", concepts: ["Stored vs Reflected vs DOM XSS", "Context-Aware Output Encoding", "Content Security Policy (CSP)", "HttpOnly Cookies"], ans: "XSS injects malicious client-side script. Stored XSS saves payload in DB; Reflected reflects payload via URL; DOM manipulates client DOM. Defense: context-aware output encoding, strict CSP headers, and HttpOnly session cookies." },
      { q: "What is SQL Injection (SQLi)? How do Parameterized Queries (Prepared Statements) completely neutralize it?", diff: "Intermediate", concepts: ["SQL Injection", "Parameterized Queries", "Query Pre-compilation", "ORM Best Practices"], ans: "SQLi manipulates backend database query logic via unsanitized input. Parameterized queries pre-compile the SQL statement template so user input is strictly treated as data literals rather than executable commands." },
      { q: "Explain the MITRE ATT&CK Framework and how security operations teams use it for threat hunting and gap analysis.", diff: "Intermediate", concepts: ["Tactics, Techniques, and Procedures (TTPs)", "Threat Hunting", "Detection Engineering"], ans: "MITRE ATT&CK categorizes real-world adversary behavior across the attack lifecycle (Initial Access -> Execution -> Persistence -> Lateral Movement -> Exfiltration). SOC teams map detections to identify telemetry blind spots." },
      { q: "How do you detect and defend against Pass-the-Hash (PtH) and Kerberos Golden Ticket attacks in Active Directory?", diff: "Intermediate", concepts: ["NTLM Hash Relay", "Kerberos KRBTGT Account", "Credential Guard", "Tiered Admin Architecture"], ans: "PtH reuses captured NTLM hashes. Golden Ticket uses compromised KRBTGT hash to forge Kerberos TGT tickets. Defense: enable Windows Credential Guard, implement Tiered Administrative Model (Tier 0/1/2), and rotate KRBTGT password regularly." },
      { q: "What is Zero Trust Architecture (NIST SP 800-207), and what are its core tenets (Never Trust, Always Verify)?", diff: "Intermediate", concepts: ["NIST SP 800-207", "Micro-Segmentation", "Continuous Posture Evaluation", "mTLS Authentication"], ans: "Zero Trust assumes the internal network is hostile. Core tenets: authenticate and authorize every transaction dynamically based on device health, user identity, context, and enforce granular micro-segmentation." },
      { q: "Explain the mechanics of a Man-in-the-Middle (MitM) attack over HTTPS and how TLS Certificate Pinning and HSTS prevent it.", diff: "Intermediate", concepts: ["TLS Handshake", "Certificate Pinning", "HSTS Header", "ARP Spoofing"], ans: "MitM intercepts plaintext communication by spoofing certificates or DNS. HSTS forces browsers to use only HTTPS, and Certificate Pinning validates server certificate public key hashes directly against application binaries." },
      { q: "What is Cross-Site Request Forgery (CSRF), and how do SameSite cookie attributes and Anti-CSRF Synchronizer Tokens prevent it?", diff: "Intermediate", concepts: ["CSRF Exploitation", "SameSite=Strict/Lax", "Synchronizer Token Pattern", "Custom Request Headers"], ans: "CSRF tricks an authenticated browser into submitting unauthorized requests to a trusted site. Prevented by SameSite=Strict cookies and unique, cryptographically random Anti-CSRF tokens validated on state-changing requests." },
      { q: "Detail an advanced incident response and containment framework for an active enterprise ransomware outbreak.", diff: "Advanced", concepts: ["IR Lifecycle (NIST 800-61)", "Network Isolation", "VSS Backup Preservation", "Threat Eradication"], ans: "1. Immediate containment: isolate infected subnets and disable compromised AD accounts. 2. Preserve forensic volatile memory. 3. Audit immutable/offline backups. 4. Identify initial access vector (phishing, RDP, zero-day). 5. Rebuild from clean golden images." },
      { q: "How do you implement and monitor eBPF (Extended Berkeley Packet Filter) for real-time Linux kernel telemetry and container security?", diff: "Advanced", concepts: ["eBPF Probes (kprobes/tracepoints)", "Kernel Telemetry", "Container Escape Detection", "Cilium / Falco"], ans: "eBPF runs sandboxed bytecode inside Linux kernel, monitoring syscalls, network sockets, and file operations without kernel module overhead, enabling instant detection of privilege escalations and container escapes." },
      { q: "How does Public Key Infrastructure (PKI) handle Certificate Revocation (CRLs vs OCSP vs OCSP Stapling)?", diff: "Advanced", concepts: ["X.509 Certificates", "CRL Bandwidth Overhead", "OCSP Latency & Privacy", "OCSP Stapling"], ans: "CRLs publish lists of revoked certs (heavy bandwidth). OCSP checks revocation status in real-time but introduces latency and privacy leakage. OCSP Stapling has the web server include a time-stamped CA-signed OCSP response in the TLS handshake." },
      { q: "What are the security implications of Post-Quantum Cryptography (PQC), and what algorithms (Kyber, Dilithium) are standardized by NIST?", diff: "Advanced", concepts: ["Shor's Algorithm vs RSA/ECC", "Lattice-Based Cryptography", "ML-KEM (Kyber)", "ML-DSA (Dilithium)"], ans: "Quantum computers using Shor's algorithm will break RSA and ECC. NIST standardized lattice-based algorithms: ML-KEM (CRYSTALS-Kyber) for general encryption/key exchange and ML-DSA (CRYSTALS-Dilithium) for digital signatures." },
      { q: "How do you detect and defend against Server-Side Request Forgery (SSRF) in cloud AWS environments (IMDSv1 vs IMDSv2)?", diff: "Advanced", concepts: ["SSRF Exploitation", "AWS Metadata (169.254.169.254)", "IMDSv2 Session Token", "Egress Filtering"], ans: "SSRF forces backend servers to fetch internal URLs. In AWS, attackers target EC2 metadata to steal IAM role credentials. Enforce IMDSv2 which requires PUT request with session token and hop limit of 1." },
    ],
    problemSolving: [
      { q: "Your SIEM alerts on multiple outbound DNS requests with random high-entropy subdomains (e.g. x7f9a2.attacker.com). How do you analyze this?", diff: "Intermediate", concepts: ["DNS Tunneling / Data Exfiltration", "Entropy Analysis", "PCAP Investigation", "Sinkholing"], ans: "Diagnose DNS tunneling or Command & Control (C2) beaconing. Extract domain entropy scores, inspect DNS query payload in PCAP for base64 encoded chunks, isolate host IP, and sinkhole domain at enterprise DNS resolver." },
      { q: "A critical external web server is found vulnerable to a remote code execution (RCE) zero-day exploit with no vendor patch available. How do you mitigate this?", diff: "Intermediate", concepts: ["Virtual Patching / WAF Rule", "Network Micro-Segmentation", "Compensating Controls"], ans: "Deploy an immediate custom virtual patch on WAF to block exploit payload signatures, isolate web server into restricted VLAN with outbound egress blocking, and enable strict AppArmor/SELinux profiles." },
      { q: "Analyze a scenario where an attacker bypassed Multi-Factor Authentication (MFA) via MFA Prompt Fatigue / Push Bombing. How do you solve this?", diff: "Intermediate", concepts: ["MFA Fatigue / Push Bombing", "Number Matching", "FIDO2 / WebAuthn Hardware Keys", "Conditional Access"], ans: "Attackers spam push notifications until user approves. Eliminate simple push approvals by enforcing Number Matching (typing on-screen code), or upgrade to phishing-resistant FIDO2/WebAuthn hardware security keys." },
      { q: "A developer accidentally pushed an AWS production secret access key to a public GitHub repository. What is your immediate incident response?", diff: "Intermediate", concepts: ["Credential Revocation", "CloudTrail Audit", "Secret Rotation", "Pre-Commit Hooks"], ans: "1. Immediately revoke and delete the exposed AWS IAM key. 2. Audit AWS CloudTrail logs for unauthorized API calls since commit timestamp. 3. Rotate affected database/service credentials. 4. Implement automated secret scanning and Git pre-commit hooks." },
      { q: "During threat hunting, you discover an unapproved PowerShell script executing with encoded commands (`-EncodedCommand`) on a domain controller. How do you triage?", diff: "Advanced", concepts: ["PowerShell Script Block Logging", "Base64 Decoding", "Memory Forensics", "AD Triage"], ans: "Capture volatile memory, extract and base64-decode the command string from Windows Event ID 4104 (Script Block Logging), check network sockets for active reverse shell beacons, and isolate the DC immediately." },
      { q: "How would you design a secure CI/CD pipeline ensuring Software Supply Chain Security (SLSA framework, SBOM, Sigstore)?", diff: "Advanced", concepts: ["SLSA Framework", "Software Bill of Materials (SBOM)", "Sigstore / Cosign", "Dependency Pinning"], ans: "Generate CycloneDX/SPDX SBOMs during build, sign build artifacts using Sigstore/Cosign with ephemeral OIDC tokens, enforce pinned dependency hashes, and block unverified container images in Kubernetes." },
      { q: "An employee falls for a spear-phishing email and clicks a link that steals their browser session cookies. How do you invalidate their access?", diff: "Intermediate", concepts: ["Session Invalidation", "Token Revocation", "OAuth Grant Audit", "Conditional Access Token Lifetime"], ans: "Revoke active user refresh tokens in Identity Provider (Entra ID / Okta), force global sign-out, terminate active browser sessions, audit recently granted OAuth app permissions, and enforce Continuous Access Evaluation (CAE)." },
      { q: "A production Kubernetes cluster experiences an alert where a pod is attempting to mount `/var/run/docker.sock` and access host namespaces. How do you investigate?", diff: "Advanced", concepts: ["Container Escape Analysis", "Pod Security Standards", "Admission Controller (OPA/Kyverno)", "Host Path Mounts"], ans: "Mounting docker.sock allows total node takeover. Terminate the pod, inspect the deployment manifest, enforce Pod Security Admission (restricted profile), and deploy OPA Gatekeeper/Kyverno policies blocking hostPath volume mounts." },
      { q: "Design a secure multi-region disaster recovery strategy for cryptographic key material stored in Hardware Security Modules (HSMs).", diff: "Advanced", concepts: ["HSM Key Wrapping", "FIPS 140-2 Level 3", "M-of-N Quorum Access", "Cross-Region Sync"], ans: "Utilize FIPS 140-2/3 Level 3 HSMs with asymmetric key wrapping (AES-KWP), enforce M-of-N multi-party quorum activation cards, and replicate encrypted key material securely over dedicated private VPN/DirectConnect tunnels." },
      { q: "A distributed denial of service (DDoS) attack saturates your 10 Gbps ISP link with BGP amplification traffic. How do you defend?", diff: "Advanced", concepts: ["BGP Anycast Routing", "Cloud Scrubbing Centers", "BGP Blackholing / Flowspec", "Rate Limiting"], ans: "Route traffic through upstream Cloud Scrubbing centers (Cloudflare/Akamai) using BGP Anycast, leverage BGP Flowspec to drop malicious UDP reflection vectors at ISP edge, and apply geo-blocking rate limits." },
      { q: "You discover an attacker has created a hidden persistence mechanism via a Windows Scheduled Task and WMI Event Subscription. How do you eradicate it?", diff: "Intermediate", concepts: ["WMI Event Filter / Consumer", "Autoruns Inspection", "Sysmon Telemetry", "Remediation Script"], ans: "Use Sysmon Event ID 19/20/21 and PowerShell `Get-CimInstance __EventFilter` to locate malicious WMI filters and consumers, remove correlated registry Run keys and Scheduled Tasks, and verify with Microsoft Autoruns." },
      { q: "Scenario: A penetration test identifies an Insecure Direct Object Reference (IDOR) on your user account endpoint `/api/users/1054/profile`. How do you remediate?", diff: "Intermediate", concepts: ["IDOR Remediation", "Session Ownership Check", "UUID vs Incremental IDs", "Policy-Based Access"], ans: "Never trust user-supplied ID parameters in request URLs. Replace incremental integer IDs with UUIDv4, and implement server-side authorization checks verifying `request.session.user.id === resource.owner_id`." },
    ],
    behavioral: [
      { q: "Describe a high-stress security incident where you had to manage executive communications while coordinating technical containment.", diff: "Intermediate", concepts: ["STAR Method", "Crisis Communication", "Incident Coordination"], ans: "Detail the Situation, Task, Action (establishing hourly executive SITREPs while keeping technical IR war room isolated from distractions), and Result (successful containment within SLA with zero data breach)." },
      { q: "Tell me about a time you had to enforce a strict security policy that met severe resistance from software developers or business units.", diff: "Intermediate", concepts: ["Stakeholder Negotiation", "Security vs Usability", "Pragmatic Security"], ans: "Explain actively listening to their workflow friction, implementing automated security scanning in their native IDE/CI tools rather than manual gatekeeping, and gaining mutual agreement." },
      { q: "Describe a situation where you discovered a vulnerability in production that could not be immediately patched due to business uptime constraints.", diff: "Intermediate", concepts: ["Risk Assessment", "Compensating Controls", "Risk Acceptance"], ans: "Walk through calculating CVSS/business impact, proposing temporary compensating controls (WAF rule + enhanced SIEM alerting), and getting formal sign-off from the CISO and engineering lead." },
      { q: "How do you stay updated with emerging CVE zero-day vulnerabilities, threat actor TTPs, and security research?", diff: "Basic", concepts: ["Continuous Learning", "Threat Intelligence Feeds", "Community Engagement"], ans: "Mention following CISA KEV catalog, vendor security advisories, participating in CTFs/Defcon/BlackHat briefings, and subscribing to reputable security research blogs." },
      { q: "Tell me about a time you made an incorrect assumption during an incident investigation. How did you identify and correct your mistake?", diff: "Intermediate", concepts: ["Humility", "Scientific Method", "Evidence-Based IR"], ans: "Explain realizing that initial telemetry pointed to a false positive, pivoting back to raw PCAP/endpoint logs without ego, identifying the true root cause, and documenting post-mortem lessons learned." },
      { q: "Describe a successful security awareness initiative you spearheaded that improved organization-wide phishing reporting rates.", diff: "Intermediate", concepts: ["Security Culture", "Gamification", "Positive Reinforcement"], ans: "Detail designing realistic contextual phishing simulations, providing instant 1-click reporting buttons, and rewarding top-reporting departments rather than shaming users." },
      { q: "How do you handle disagreements with external compliance auditors regarding interpretations of SOC 2 or ISO 27001 controls?", diff: "Intermediate", concepts: ["Compliance Alignment", "Audit Defense", "Evidence Gathering"], ans: "Provide clear, documented technical evidence demonstrating that the existing technical implementation achieves the control objective (intent of the standard) through alternative compensating controls." },
      { q: "Describe a time you mentored a junior security analyst on triage protocols, log analysis, or threat hunting.", diff: "Intermediate", concepts: ["Mentorship", "Knowledge Transfer", "Playbook Authoring"], ans: "Explain pairing on live triage alerts, teaching Boolean search logic in SIEM, and collaborating on standardized runbooks to empower their independent decision-making." },
      { q: "Tell me about a time you advocated for investing in a new security tool or architecture upgrade. How did you build the business case?", diff: "Advanced", concepts: ["Business Case", "Risk ROI", "Cost-Benefit Analysis"], ans: "Calculate financial risk exposure using annual loss expectancy (ALE = SLE * ARO), demonstrate operational hours saved through automation, and present clear vendor comparison benchmarks." },
      { q: "Describe an experience where you had to conduct a sensitive internal fraud or insider threat investigation.", diff: "Advanced", concepts: ["Discretion", "Chain of Custody", "Legal Coordination"], ans: "Emphasize strict confidentiality, maintaining cryptographic chain of custody for digital evidence, coordinating directly with Legal/HR, and compiling an objective factual dossier." },
    ],
    situational: [
      { q: "Scenario: A third-party SaaS vendor used by your company suffers a major data breach exposing API tokens. What are your immediate actions?", diff: "Intermediate", concepts: ["Vendor Risk IR", "Token Invalidation", "Scope Analysis"], ans: "1. Immediately rotate and revoke all shared API keys and OAuth tokens. 2. Audit access logs for token usage. 3. Review vendor contract/DPA. 4. Request vendor forensics report to verify data blast radius." },
      { q: "Scenario: A critical production server becomes unresponsive during business hours and an unknown SSH key is found in `~/.ssh/authorized_keys`. What do you do?", diff: "Intermediate", concepts: ["Containment", "Memory Dump", "Lateral Movement Check"], ans: "Isolate network interface immediately (do not reboot). Capture RAM dump for live memory analysis. Remove the unauthorized key. Check auth.log for initial ingress IP and audit all other servers for the same key." },
      { q: "Scenario: The CEO forwards an urgent email asking for an immediate wire transfer to a new vendor bank account. How do you handle this?", diff: "Basic", concepts: ["Business Email Compromise (BEC)", "Out-of-Band Verification", "Header Analysis"], ans: "Recognize classic BEC fraud. Inspect email headers for spoofed SPF/DKIM/DMARC alignment. Verify the wire request directly with the CEO via out-of-band communication (phone/in-person), and alert finance." },
      { q: "Scenario: An employee accidentally uploads an internal spreadsheet containing 10,000 customer PII records to a public Dropbox link. What is your response?", diff: "Intermediate", concepts: ["PII Data Breach", "Link Revocation", "Regulatory Notification (GDPR/CCPA)"], ans: "1. Terminate public Dropbox link and revoke file permissions. 2. Audit access logs to count unique external downloads. 3. Notify Legal/Privacy Officer to evaluate mandatory 72-hour breach reporting thresholds under GDPR/CCPA." },
      { q: "Scenario: Your endpoint detection (EDR) agent alerts that Mimikatz was executed in memory on a workstation in the finance department. What do you do?", diff: "Intermediate", concepts: ["Credential Dumping", "Host Isolation", "AD Credential Reset"], ans: "Remotely isolate the workstation from network via EDR console. Force immediate password and Kerberos ticket reset for all accounts that logged onto that machine. Search AD logs for lateral SMB/WMI connections." },
      { q: "Scenario: A developer refuses to fix a high-severity vulnerability before a scheduled product release because it would delay launch by 4 days. How do you proceed?", diff: "Intermediate", concepts: ["Risk Escalation", "Compensating Controls", "Executive Alignment"], ans: "Assess whether a temporary WAF/network compensating control can safely mitigate risk. If not, present residual risk to the VP of Engineering and CISO for formal risk acceptance or agreed launch delay." },
      { q: "Scenario: Threat intelligence reveals that your company credentials and session cookies are currently being sold on a dark web marketplace. What is your protocol?", diff: "Intermediate", concepts: ["Dark Web Triage", "Global Password Reset", "Infostealer Malware Check"], ans: "Identify affected employee usernames. Trigger immediate forced password reset and revoke all active session tokens. Scan employee devices for infostealer malware (RedLine/Vidar), and enforce hardware MFA." },
      { q: "Scenario: A rogue Wi-Fi Access Point broadcasting your corporate SSID (Evil Twin) is detected in the building parking lot. How do you respond?", diff: "Intermediate", concepts: ["Rogue AP / Evil Twin", "WPA3 Enterprise (802.1X)", "Radio Triangulation"], ans: "Enforce 802.1X EAP-TLS certificate-based authentication so devices never authenticate to untrusted APs. Use wireless intrusion detection (WIDS) to locate rogue BSSID, and send physical security." },
      { q: "Scenario: Your organization receives an anonymous extortion email claiming they exfiltrated your source code and will publish it in 24 hours. What are your steps?", diff: "Advanced", concepts: ["Extortion Triage", "Proof of Life Validation", "Egress Log Analysis"], ans: "1. Demand proof of exfiltration without paying. 2. Correlate claimed repository names with DLP and egress firewall logs for massive outbound data spikes. 3. Involve Legal, Cyber Insurance, and FBI Cyber Division." },
      { q: "Scenario: A penetration tester demonstrates that your mobile app API allows unrestricted rate-less password guessing. How do you remediate?", diff: "Basic", concepts: ["Rate Limiting", "Account Lockout / CAPTCHA", "IP Reputation Filtering"], ans: "Implement progressive rate limiting on API gateway (Redis Token Bucket), enforce CAPTCHA after 3 failed attempts, implement smart IP reputation filtering, and notify users of suspicious login attempts." },
    ],
    roleSpecific: [
      { q: "What industry frameworks and standards govern cybersecurity programs (NIST CSF, ISO 27001, CIS Critical Security Controls, PCI-DSS)?", diff: "Basic", concepts: ["NIST Cybersecurity Framework", "ISO/IEC 27001 ISMS", "CIS Top 18", "PCI-DSS v4.0"], ans: "NIST CSF provides Identify/Protect/Detect/Respond/Recover structure; ISO 27001 provides formal ISMS certification; CIS Controls provide prioritized technical hardening benchmarks; PCI-DSS governs credit card security." },
      { q: "How do you configure and tune SIEM correlation rules (Elastic Security / Splunk) to maximize detection fidelity while minimizing false positives?", diff: "Intermediate", concepts: ["SIEM Correlation Rules", "Statistical Baselines", "Thresholding & Tuning", "Alert-to-Noise Ratio"], ans: "Define specific high-fidelity logic using MITRE techniques, establish statistical baseline thresholds for normal user behavior, whitelist legitimate automated admin service accounts, and review false positive metrics weekly." },
      { q: "What are the core capabilities and architecture of Security Orchestration, Automation, and Response (SOAR) playbooks?", diff: "Intermediate", concepts: ["SOAR Architecture", "Automated Enrichment", "Threat Intel Lookups", "Playbook Branching"], ans: "SOAR connects SIEM alerts to automated playbooks: automatically extracting IPs/hashes, querying VirusTotal/AlienVault, quarantining infected endpoints, and opening Jira tickets to reduce mean time to respond (MTTR)." },
      { q: "How do you evaluate and implement Cloud Security Posture Management (CSPM) and Cloud Workload Protection (CWPP) across AWS/Azure?", diff: "Intermediate", concepts: ["CSPM vs CWPP", "Misconfiguration Detection", "Runtime Agent Telemetry", "IAM Least Privilege"], ans: "CSPM scans cloud control plane configurations (public S3 buckets, open security groups, unencrypted EBS); CWPP secures runtime workloads (containers, EC2 VMs, serverless functions) with real-time behavioral protection." },
      { q: "Explain the architecture and security controls of an Enterprise Identity and Access Management (IAM) system using SAML 2.0 and OIDC.", diff: "Intermediate", concepts: ["SAML 2.0 XML Assertions", "OpenID Connect (OIDC) JWT", "IdP vs SP", "Token Signing Keys"], ans: "SAML uses XML assertions for enterprise SSO across legacy apps; OIDC builds on OAuth 2.0 using JSON Web Tokens (ID Tokens) for modern web/mobile APIs. Both rely on asymmetric digital signatures for trust." },
      { q: "How do you perform a Threat Model using STRIDE methodology on a new microservices payment processing architecture?", diff: "Advanced", concepts: ["STRIDE Methodology", "Data Flow Diagrams (DFD)", "Trust Boundaries", "Threat Mitigation"], ans: "Map architecture with Data Flow Diagrams and trust boundaries. Apply STRIDE (Spoofing, Tampering, Repudiation, Information Disclosure, Denial of Service, Elevation of Privilege) to each element and assign mitigations." },
      { q: "What are the best practices for implementing Secure Software Development Lifecycle (SSDLC) tools (SAST, DAST, SCA, IAST)?", diff: "Intermediate", concepts: ["SAST vs DAST", "Software Composition Analysis (SCA)", "IAST", "Shift-Left Security"], ans: "SAST scans source code for syntax flaws during PRs; SCA identifies vulnerable third-party open-source libraries; DAST probes running staging environments; IAST instruments runtime application bytecode." },
      { q: "How do you architect an enterprise Network Access Control (NAC) system utilizing 802.1X, RADIUS, and dynamic VLAN assignment?", diff: "Advanced", concepts: ["802.1X EAP-TLS", "RADIUS / TACACS+", "Dynamic VLAN Assignment", "Device Posture Assessment"], ans: "Enforce 802.1X port security with machine certificates. RADIUS authenticates client, checks MDM compliance posture, and instructs network switch to dynamically assign client to corporate, IoT, or quarantine VLAN." },
      { q: "Explain the forensic acquisition and analysis process for volatile physical RAM memory using Volatility 3.", diff: "Advanced", concepts: ["Memory Capture (LiME / WinPmem)", "Volatility 3 Plugins", "Process Tree Analysis", "Malfind Injection Detection"], ans: "Capture RAM using WinPmem/LiME to preserve volatile state. In Volatility 3: inspect `windows.pstree` for anomalous parent-child relationships, `windows.malfind` for injected shellcode, and `windows.netscan` for active connections." },
      { q: "What strategies and telemetry data points do you use to detect and mitigate Advanced Persistent Threat (APT) living-off-the-land binaries (LOLBins)?", diff: "Advanced", concepts: ["LOLBins / LOLScripts", "Certutil, Bitsadmin, Mshta", "Command Line Auditing", "Behavioral Whitelisting"], ans: "APTs use legitimate built-in tools (certutil, bitsadmin, mshta, powershell) to bypass antivirus. Detect via Sysmon Event ID 1 parent-process ancestry, command line argument auditing, and AppLocker script enforcement." },
    ],
  },

  software: {
    technical: [
      { q: "What are the core differences between Synchronous and Asynchronous execution in JavaScript? Explain the Event Loop, Call Stack, and Microtask Queue.", diff: "Basic", concepts: ["Event Loop", "Call Stack", "Microtask Queue", "Promises / async-await"], ans: "Single-threaded JS executes synchronous code on the call stack. Async operations (fetch, timers) delegate to Web APIs. Resolved Promises go to the Microtask queue (executed immediately after current stack frame), while setTimeout goes to the Macrotask queue." },
      { q: "What are the fundamental HTTP methods in RESTful API design, and what are standard HTTP status codes for success, redirection, client error, and server error?", diff: "Basic", concepts: ["REST APIs", "GET/POST/PUT/PATCH/DELETE", "Status Code Categories"], ans: "GET (read), POST (create), PUT (replace), PATCH (partial update), DELETE (remove). 200 (OK), 201 (Created), 301 (Moved Permanently), 400 (Bad Request), 401 (Unauthorized), 403 (Forbidden), 404 (Not Found), 500 (Internal Server Error)." },
      { q: "What is the difference between Primitive and Reference data types in JavaScript? How does memory allocation differ between Stack and Heap?", diff: "Basic", concepts: ["Primitives vs References", "Stack vs Heap Memory", "Pass by Value vs Reference"], ans: "Primitives (string, number, boolean, null, undefined, symbol, bigint) store values directly on the stack. Reference types (objects, arrays, functions) allocate memory on the heap and store a pointer address on the stack." },
      { q: "What are Git Merge and Git Rebase? When would you choose one over the other in team feature branch workflows?", diff: "Basic", concepts: ["Git Merge vs Rebase", "Commit History", "Fast-Forward", "Merge Commits"], ans: "Git Merge combines branches by creating a merge commit preserving exact historical timestamps. Git Rebase reapplies feature commits on top of main, creating a linear history. Rebase is preferred for local feature branches before PR; Merge for release integration." },
      { q: "How does React's Virtual DOM and Reconciliation algorithm (Fiber) work, and why are unique keys essential when rendering dynamic lists?", diff: "Intermediate", concepts: ["Virtual DOM", "Diffing Algorithm", "Fiber Architecture", "Stable Keys"], ans: "React creates a lightweight in-memory VDOM representation. Fiber breaks rendering into incremental, interruptible units. Keys give elements stable identities across renders so React can move rather than destroy/recreate DOM nodes." },
      { q: "What are the architectural trade-offs between Relational Databases (PostgreSQL) and NoSQL Document Stores (MongoDB)? How do you ensure ACID transactions?", diff: "Intermediate", concepts: ["ACID Properties", "Relational Integrity", "Indexing", "Document Modeling"], ans: "PostgreSQL enforces rigid relational schemas, foreign key integrity, and ACID guarantees for transactional consistency. MongoDB offers flexible JSON documents and horizontal sharding for high-write polymorphic datasets." },
      { q: "How do you implement secure stateless user authentication using JSON Web Tokens (JWT) and bcrypt password hashing in an Express/Node.js backend?", diff: "Intermediate", concepts: ["JWT Signing & Verification", "Bcrypt Salt Rounds", "Authorization Bearer Header", "Auth Middleware"], ans: "Hash passwords with bcrypt (>= 10-12 salt rounds). On valid login, sign JWT containing user payload with private HMAC secret and expiry. Validate Bearer token in Express middleware and attach user to request object." },
      { q: "Explain database indexing in PostgreSQL. How does a B-Tree index accelerate SELECT queries, and what is the write overhead on INSERT/UPDATE?", diff: "Intermediate", concepts: ["PostgreSQL B-Tree Index", "Index Scan vs Seq Scan", "Write Amplification", "Composite Indexes"], ans: "B-Tree indexes provide O(log N) lookups by maintaining sorted balanced tree pages. Speeds up WHERE, ORDER BY, and JOIN queries, but introduces write amplification because every INSERT/UPDATE must re-balance index trees." },
      { q: "What is Cross-Origin Resource Sharing (CORS), why do browsers enforce same-origin policy, and how do you configure CORS securely in Express?", diff: "Intermediate", concepts: ["CORS Headers", "Preflight OPTIONS Request", "Same-Origin Policy", "Access-Control-Allow-Origin"], ans: "Same-origin policy restricts cross-origin DOM/fetch access. Preflight OPTIONS requests verify server permissions. Securely configure `Access-Control-Allow-Origin` to specific trusted domains and specify allowed methods and credentials." },
      { q: "How would you design a scalable caching architecture using Redis to accelerate slow database queries and mitigate high read traffic?", diff: "Advanced", concepts: ["Cache-Aside Pattern", "TTL Expiration", "Cache Invalidation", "Cache Stampede (Mutex Locks)"], ans: "Implement Cache-Aside: check Redis first; on miss, query DB and populate Redis with TTL. Invalidate cache on mutations. Prevent cache stampede using distributed mutex locks or probabilistic early expiration." },
      { q: "What strategies and architectural patterns do you use to optimize Frontend Core Web Vitals (Largest Contentful Paint & Interaction to Next Paint)?", diff: "Advanced", concepts: ["Code Splitting (React.lazy)", "Bundle Size Reduction", "Image Compression (WebP)", "INP Event Optimization"], ans: "Implement route-based code splitting with React.lazy/dynamic imports, compress images to WebP/AVIF with explicit dimensions, preload critical fonts, eliminate render-blocking CSS, and yield main thread during heavy calculations." },
      { q: "Scenario: In production, an API endpoint latency spikes from 150ms to 4500ms under heavy concurrent user load. How would you systematically diagnose and resolve the bottleneck?", diff: "Advanced", concepts: ["APM Profiling", "PostgreSQL EXPLAIN ANALYZE", "Database Connection Pool Saturation", "Slow Queries"], ans: "1. Check server CPU/memory and connection pool saturation. 2. Inspect APM distributed traces to isolate slow layer. 3. Run `EXPLAIN (ANALYZE, BUFFERS)` on SQL queries to find sequential table scans. 4. Add missing composite indexes and optimize pool size." },
      { q: "How do you implement microservice inter-service communication using event-driven architectures with Apache Kafka or RabbitMQ?", diff: "Advanced", concepts: ["Message Queues vs Event Streams", "Idempotent Consumers", "Transactional Outbox Pattern", "Dead Letter Queues"], ans: "Decouple services asynchronously. Producers publish domain events to Kafka topics; consumers process events with idempotent keys. Use Transactional Outbox pattern to atomically save database state and publish events." },
      { q: "Scenario: Design a high-throughput URL Shortener service (like bit.ly) handling 100,000 write requests per second. Detail database sharding, base62 encoding, and cache layers.", diff: "Advanced", concepts: ["System Design", "Base62 Encoding & Snowflake IDs", "Database Sharding", "Distributed Caching"], ans: "Generate 64-bit distributed IDs using Twitter Snowflake, encode to Base62 (7 characters), shard database by ID hash, place Redis LRU cache in front of DB, and serve redirects with 301/302 headers." },
      { q: "Explain the differences between Optimistic and Pessimistic Concurrency Control in relational database transactions.", diff: "Advanced", concepts: ["Optimistic Concurrency (Row Versioning)", "Pessimistic Locking (SELECT FOR UPDATE)", "Lost Updates"], ans: "Optimistic uses version numbers/timestamps and validates before commit (retries on conflict; ideal for low write contention). Pessimistic acquires explicit row-level exclusive locks (`SELECT ... FOR UPDATE`), blocking other transactions." },
      { q: "How do React 18 Concurrency features (`useTransition`, `useDeferredValue`) improve UI responsiveness during heavy rendering?", diff: "Advanced", concepts: ["Interruptible Rendering", "Transition Priority", "Suspense Boundaries"], ans: "Concurrent React marks non-urgent state updates with `useTransition`, allowing user input events (typing, clicks) to interrupt background rendering and prevent UI jank." },
      { q: "What are the trade-offs between Monolithic, Microservices, and Serverless architectures? When is each appropriate?", diff: "Advanced", concepts: ["Monolith vs Microservices", "Cold Starts", "Operational Complexity", "Domain-Driven Design"], ans: "Monoliths offer simple deployments and transactional integrity (best for early-stage); Microservices enable independent scaling and team autonomy at the cost of distributed complexity; Serverless eliminates infrastructure management for event-driven burst workloads." },
      { q: "How do you design and secure WebSocket architectures for high-concurrency bi-directional real-time communication?", diff: "Advanced", concepts: ["WebSocket Protocol", "Connection State Management", "Redis Pub/Sub Clustering", "Heartbeats & Auth"], ans: "Authenticate WebSocket connection during initial HTTP upgrade handshake using short-lived tokens. Scale across multiple server nodes using Redis Pub/Sub cluster backplane, and maintain heartbeat pings to clean up zombie sockets." },
    ],
    problemSolving: [
      { q: "You discover a memory leak in a Node.js production service causing heap memory to grow until out-of-memory crash. How do you isolate it?", diff: "Advanced", concepts: ["Heap Snapshots (Chrome DevTools)", "V8 Memory Profiler", "Event Listener Accumulation", "Global Closures"], ans: "Capture heap snapshots before and after load testing using `v8` or `--inspect`. Compare snapshots in Chrome DevTools to locate uncollected objects (e.g. growing global arrays, uncleared setInterval callbacks, or detached event listeners)." },
      { q: "Design a distributed rate limiter that restricts API clients to 100 requests per minute across a cluster of 10 backend servers.", diff: "Intermediate", concepts: ["Token Bucket Algorithm", "Redis Lua Scripting", "Sliding Window Counter", "Race Condition Prevention"], ans: "Implement Sliding Window Counter in Redis using atomic Lua scripts (ZADD, ZREMRANGEBYSCORE, ZCARD). Atomic execution guarantees accurate counts across all 10 server nodes without race conditions." },
      { q: "A SQL query joining four tables takes 12 seconds to run. Walk through your query optimization process using EXPLAIN ANALYZE.", diff: "Intermediate", concepts: ["EXPLAIN ANALYZE", "Seq Scan vs Index Scan", "Nested Loop vs Hash Join", "Covering Indexes"], ans: "Run EXPLAIN ANALYZE to identify the slowest node. Check for Sequential Scans on large tables, excessive disk spills during Hash Joins, and high buffer reads. Create multi-column covering indexes and rewrite subqueries to JOINs." },
      { q: "How would you implement zero-downtime database schema migrations for adding a NOT NULL column with a default value to a 50-million-row table?", diff: "Advanced", concepts: ["Zero-Downtime Migrations", "PostgreSQL Table Locks", "Multi-Phase Migration", "Backfill Batching"], ans: "1. Add column as NULLable without default. 2. Backfill existing rows in small asynchronous batches. 3. Add default value for new inserts. 4. Add NOT NULL constraint with `VALIDATE CONSTRAINT` to avoid exclusive table locks." },
      { q: "Design a fault-tolerant webhook delivery system that reliably retries failed customer endpoints with exponential backoff.", diff: "Intermediate", concepts: ["Dead Letter Queue", "Exponential Backoff & Jitter", "HMAC Signature Verification", "Idempotency"], ans: "Queue webhook payloads in RabbitMQ/SQS. Worker attempts delivery with HMAC SHA-256 header. On failure (5xx/timeout), retry with exponential backoff + jitter up to 5 times. Move permanent failures to DLQ for manual inspection." },
      { q: "An application experiences high database connection timeouts during peak traffic hours. How do you optimize the connection pool?", diff: "Intermediate", concepts: ["Connection Pooling (PgBouncer)", "HikariCP / Node-pg Pool", "Max Connections vs CPU Cores", "Query Saturation"], ans: "Analyze active vs idle connections. Increase PgBouncer transaction-level pooling in front of DB, tune pool size formula (connections = (cores * 2) + effective_spindle_count), and set strict query statement timeouts." },
      { q: "How do you implement optimistic locking in an e-commerce inventory checkout system to prevent overselling limited stock items?", diff: "Intermediate", concepts: ["Optimistic Locking", "Atomic Conditional UPDATE", "Inventory Concurrency", "Race Condition Mitigation"], ans: "Execute atomic conditional SQL: `UPDATE inventory SET stock = stock - 1 WHERE item_id = :id AND stock >= 1`. If rows affected is 0, stock is exhausted; return out-of-stock immediately without deadlock." },
      { q: "Scenario: Two microservices need to perform an atomic business transaction (e.g. Order Service and Payment Service). How do you use the Saga Pattern?", diff: "Advanced", concepts: ["Saga Pattern (Choreography vs Orchestration)", "Compensating Transactions", "Eventual Consistency"], ans: "Implement Orchestrated Saga: Saga orchestrator calls Order Service -> calls Payment Service. If payment fails, orchestrator executes compensating transactions (canceling order, releasing inventory) to restore eventual consistency." },
      { q: "How do you architect a real-time collaborative document editing system (like Google Docs) handling concurrent character edits?", diff: "Advanced", concepts: ["Operational Transformation (OT)", "Conflict-Free Replicated Data Types (CRDTs)", "Yjs / Automerge", "WebSocket Sync"], ans: "Utilize CRDTs (such as Yjs or Automerge) representing document characters as causally ordered nodes with unique Lamport timestamps, enabling peer-to-peer or server-mediated conflict-free convergence without locking." },
      { q: "A frontend React application is sluggish due to rendering a table with 10,000 rows. How do you optimize the rendering performance?", diff: "Intermediate", concepts: ["Windowing / Virtualization (react-window)", "useMemo / React.memo", "DOM Node Reduction"], ans: "Implement list virtualization using `react-window` or `@tanstack/react-virtual` to only render the ~20 rows currently visible in the scroll viewport, reducing DOM nodes from 10,000 to 20." },
      { q: "How do you design an automated idempotent API endpoint for processing credit card charges to prevent duplicate payments on network retries?", diff: "Intermediate", concepts: ["Idempotency-Key Header", "Atomic DB Insertion", "Payment Gateway Deduplication", "Cached Response"], ans: "Require an `Idempotency-Key` header from client. Store key in Redis/DB with processing status. If key already exists and completed, return cached response; if in-flight, return 409 Conflict; otherwise proceed with payment." },
      { q: "Describe how you would design an end-to-end full-text search engine for millions of product catalog items using Elasticsearch or PostgreSQL tsvector.", diff: "Advanced", concepts: ["Inverted Index", "Tokenization & Stemming", "BM25 Ranking", "Fuzzy Matching & Synonyms"], ans: "Configure PostgreSQL `tsvector` with GIN indexing or Elasticsearch cluster with custom analyzers (n-gram, lowercase, Porter stemmer). Score results with BM25 algorithm and update index via asynchronous CDC outbox workers." },
    ],
    behavioral: [
      { q: "Describe a high-stakes production outage you resolved. How did you coordinate with your team and communicate with leadership?", diff: "Intermediate", concepts: ["STAR Method", "Incident Management", "Post-Mortem Culture"], ans: "Walk through Situation (outage impact), Task (restoring service within SLA), Action (establishing incident commander, isolating faulty release, rolling back, running blameless post-mortem), and Result." },
      { q: "Tell me about a time you had a technical disagreement with a team member regarding software architecture or code design. How was it resolved?", diff: "Intermediate", concepts: ["Constructive Collaboration", "Proof of Concept (PoC)", "Data-Driven Consensus"], ans: "Explain focusing on quantifiable trade-offs (latency, maintainability, cost) rather than personal preferences, building small PoCs to benchmark both approaches, and aligning behind the winning data." },
      { q: "Describe a project where you inherited a legacy codebase with high technical debt and no unit tests. How did you approach refactoring?", diff: "Intermediate", concepts: ["Technical Debt Management", "Strangler Fig Pattern", "Characterization Tests"], ans: "Write characterization integration tests first to lock in existing behavior, identify highest-churn modules, apply Strangler Fig pattern to replace components incrementally, and establish CI test coverage thresholds." },
      { q: "Tell me about a time you had to deliver a software project under an aggressive timeline. What trade-offs did you make?", diff: "Intermediate", concepts: ["MVP Scoping", "Pragmatic Engineering", "Scope Negotiation"], ans: "Collaborate with product manager to cut non-essential features, focus strictly on core MVP user flows, document technical debt for immediate post-launch sprint, and deliver on schedule." },
      { q: "How do you conduct code reviews? What balance do you maintain between code quality, security, and developer velocity?", diff: "Basic", concepts: ["Code Review Culture", "Automated Linting", "Constructive Feedback"], ans: "Automate syntax and linting in CI. Focus human review on architecture, edge cases, error handling, and security. Offer clear explanations with suggestions rather than dogmatic directives." },
      { q: "Describe a time you advocated for a new technology, framework, or process that significantly improved team productivity.", diff: "Intermediate", concepts: ["Innovation", "Change Management", "Team Enablement"], ans: "Describe introducing TypeScript, automated CI/CD testing, or Docker dev environments: demonstrating tangible reductions in production bugs and onboarding time." },
      { q: "Tell me about a time you made a significant mistake that introduced a bug into production. How did you handle it?", diff: "Intermediate", concepts: ["Accountability", "Blameless Post-Mortem", "Automated Safeguards"], ans: "Take immediate ownership, push hotfix/rollback without panic, conduct a blameless post-mortem, and add automated regression tests and CI checks so the exact issue can never recur." },
      { q: "How do you stay current with rapidly evolving software frameworks, language updates, and architectural best practices?", diff: "Basic", concepts: ["Continuous Learning", "Open Source", "Technical Reading"], ans: "Follow RFC proposals, read official engineering blogs (Netflix, Uber, Discord), contribute to or study open-source repositories, and build hands-on side projects." },
      { q: "Describe an experience where you mentored a junior engineer or intern and helped them grow technically.", diff: "Intermediate", concepts: ["Mentorship", "Pair Programming", "Growth Mindset"], ans: "Schedule weekly pairing sessions, teach debugging methodologies and system design fundamentals, delegate high-visibility tasks with guidance, and celebrate their milestones." },
      { q: "Tell me about a time you had to push back against unrealistic feature requirements from a product manager or client.", diff: "Intermediate", concepts: ["Stakeholder Management", "Clear Estimation", "Alternative Solutions"], ans: "Explain the architectural complexity and risks with data-backed engineering estimates, present phased rollout alternatives, and find a compromise that delivers business value on time." },
    ],
    situational: [
      { q: "Scenario: A deployment goes live on Friday evening and introduces intermittent 500 errors affecting 5% of users. What is your immediate action?", diff: "Intermediate", concepts: ["Immediate Rollback", "Incident Triage", "Deployment Policy"], ans: "Immediately trigger an automated rollback to the previous stable release. Restore 100% availability first before investigating logs. Enforce team policy prohibiting non-emergency Friday evening deployments." },
      { q: "Scenario: Your team is split 50/50 on whether to build a new feature using GraphQL or REST APIs. How do you facilitate a decision?", diff: "Intermediate", concepts: ["Decision Matrix", "Client Requirements", "Caching & Complexity"], ans: "Evaluate client use cases: if mobile client requires granular field selection across relational data, consider GraphQL; if standard caching (CDN/HTTP) and simple endpoints suffice, choose REST." },
      { q: "Scenario: A third-party payment gateway API is experiencing a complete outage during Black Friday sales. How do you protect user experience?", diff: "Advanced", concepts: ["Circuit Breaker Pattern", "Degraded Mode", "Async Payment Queue"], ans: "Trip Circuit Breaker to avoid cascading timeouts. Switch checkout into asynchronous degraded mode: capture authorized orders in persistent queue, show clear user messaging, and process payments automatically on gateway recovery." },
      { q: "Scenario: You discover that a critical database table was accidentally created without any primary key or indexes, causing CPU at 100%. What is your fix?", diff: "Intermediate", concepts: ["Index Creation Concurrently", "Primary Key Addition", "Traffic Throttling"], ans: "Add index using `CREATE INDEX CONCURRENTLY` in PostgreSQL to avoid locking table writes. Temporarily rate-limit non-essential queries, and schedule table maintenance to add primary key constraint." },
      { q: "Scenario: A developer on your team submits a 3,000-line Pull Request containing 15 unrelated feature changes. How do you handle the review?", diff: "Basic", concepts: ["PR Sizing Best Practices", "Atomic Commits", "Constructive Guidance"], ans: "Politely request breaking the mega-PR into smaller, atomic pull requests (under 300-400 lines each) with dedicated tests, explaining that small PRs improve review thoroughness and reduce regression risk." },
      { q: "Scenario: You are tasked with migrating a 2TB production database to a new cloud provider with maximum allowed downtime of 5 minutes. What is your plan?", diff: "Advanced", concepts: ["Continuous Data Replication (CDC)", "Logical Replication", "DNS Cutover"], ans: "Set up continuous CDC logical replication (Debezium/pglogical) from old DB to new DB. Verify replication sync lag is 0ms. Put app in 2-minute maintenance mode, execute final DNS cutover, and reopen traffic." },
      { q: "Scenario: A security scan flags 15 high-severity vulnerabilities in dependencies inside `package.json` two days before release. What is your triage?", diff: "Intermediate", concepts: ["Vulnerability Triage", "Exploitability Check", "Patching / Overrides"], ans: "Check if vulnerable code paths are actually exposed/invoked in your application. Upgrade non-breaking dependencies via `npm audit fix`, apply `overrides` for transitive libraries, and implement WAF filters if upgrade breaks code." },
      { q: "Scenario: The product team requests an analytics tracking feature that would log every user keystroke across the web application. What are your concerns?", diff: "Intermediate", concepts: ["User Privacy & GDPR", "Performance Overhead", "PII Sanitization"], ans: "Raise immediate privacy and compliance concerns (GDPR/CCPA/PII leakage in password/credit card fields). Propose tracking aggregate blur/change events on non-sensitive inputs with strict data masking." },
      { q: "Scenario: A background cron job processing night reports is taking 9 hours to finish and colliding with morning user traffic. How do you fix it?", diff: "Intermediate", concepts: ["Parallel Worker Batching", "Read Replicas", "Query Chunking"], ans: "Point reporting queries to read-only database replica. Break monolithic sequential query into parallel chunked workers using worker pools/BullMQ, reducing processing time to 45 minutes." },
      { q: "Scenario: Two senior engineers are arguing in a Slack channel about code styling preferences. How do you de-escalate?", diff: "Basic", concepts: ["Automated Linters (Prettier/ESLint)", "Standardization", "Team Harmony"], ans: "De-escalate by proposing an automated tool (Prettier/ESLint) integrated into Git pre-commit hooks and CI pipelines, removing stylistic opinions from human debate entirely." },
    ],
    roleSpecific: [
      { q: "What are the core design principles of 12-Factor App methodology for cloud-native software development?", diff: "Basic", concepts: ["12-Factor Methodology", "Config in Environment", "Stateless Processes", "Port Binding"], ans: "Key factors: explicit dependencies, store config in environment variables, treat backing services as attached resources, execute app as stateless share-nothing processes, fast startup and graceful shutdown." },
      { q: "How do you configure Docker multi-stage builds to minimize production container image size and improve security?", diff: "Intermediate", concepts: ["Docker Multi-Stage", "Alpine / Distroless Base Images", "Layer Caching", "Non-Root Users"], ans: "Use builder stage with full SDK/tools to compile assets; copy only production artifacts into minimal runtime base image (Alpine or Google Distroless), and enforce `USER nonroot` for security." },
      { q: "Explain the differences between REST, GraphQL, and gRPC. What are the ideal use cases for each API protocol?", diff: "Intermediate", concepts: ["REST vs GraphQL vs gRPC", "HTTP/2 Protobuf", "Over/Under Fetching"], ans: "REST: standard CRUD over HTTP with universal caching; GraphQL: client-driven data queries avoiding over/under-fetching for rich frontends; gRPC: high-performance binary Protobuf over HTTP/2 for low-latency microservices." },
      { q: "How do you implement comprehensive observability using the Three Pillars (Metrics, Logs, and Distributed Tracing)?", diff: "Intermediate", concepts: ["Observability (OpenTelemetry)", "Prometheus / Grafana", "Structured JSON Logging", "Distributed Trace Spans"], ans: "Instrument OpenTelemetry spans across service hops with correlated trace IDs, emit structured JSON logs with trace context, and export time-series metrics (RED method: Rate, Errors, Duration) to Prometheus." },
      { q: "What is Database Sharding? Explain the difference between Range-Based, Directory-Based, and Hash-Based Sharding.", diff: "Advanced", concepts: ["Horizontal Sharding", "Consistent Hashing", "Cross-Shard Joins", "Re-Sharding"], ans: "Horizontal sharding partitions table rows across database nodes. Hash-based uses consistent hashing for uniform distribution; Range-based groups by key ranges (can cause hot spots); Directory-based uses lookup tables." },
      { q: "How do you implement Cross-Cutting Concerns (Logging, Auth, Rate Limiting, Error Handling) in backend architectures?", diff: "Intermediate", concepts: ["Middleware Pattern", "Aspect-Oriented Programming (AOP)", "API Gateways", "Interceptors"], ans: "Implement modular Express/Koa middleware pipeline or NestJS interceptors/guards, processing incoming requests sequentially and catching unhandled exceptions uniformly." },
      { q: "Explain the mechanics and advantages of Server-Side Rendering (SSR) and Incremental Static Regeneration (ISR) in Next.js.", diff: "Intermediate", concepts: ["Next.js SSR vs SSG vs ISR", "Hydration", "Edge Caching", "SEO Optimization"], ans: "SSR renders HTML on every request for dynamic data; SSG pre-builds HTML at build time for speed; ISR updates static pages in background on cache expiration without full site rebuilds." },
      { q: "How do you secure Node.js applications against Prototype Pollution and ReDoS (Regular Expression Denial of Service)?", diff: "Advanced", concepts: ["Prototype Pollution (`__proto__`)", "Object.freeze / Map", "ReDoS Catastrophic Backtracking"], ans: "Prevent prototype pollution by validating keys, using `Object.create(null)` or `Map`, and using `Object.freeze`. Prevent ReDoS by avoiding nested quantifiers like `(a+)+` and setting regex execution timeouts." },
      { q: "What strategies do you use for Database Connection Pooling in serverless environments (AWS Lambda / Vercel)?", diff: "Advanced", concepts: ["Serverless Connection Exhaustion", "AWS RDS Proxy", "Prisma Accelerate", "HTTP Database Drivers (Neon/Supabase)"], ans: "Stateless serverless containers exhaust DB connections quickly. Mitigate using connection proxy pools (AWS RDS Proxy, PgBouncer) or HTTP-based serverless drivers (Neon, PlanetScale) that reuse HTTP/2 streams." },
      { q: "How do you establish automated End-to-End (E2E) testing pipelines using Playwright or Cypress with visual regression testing?", diff: "Intermediate", concepts: ["Playwright / Cypress E2E", "Headless CI Execution", "Pixelmatch Visual Testing", "Test Fixtures"], ans: "Run headless parallel tests in GitHub Actions against seeded staging environments, capture full-page screenshot diffs with pixel thresholding to catch visual regressions, and mock third-party payment APIs." },
    ],
  },
};

// =========================================================================
// 2. UNIVERSAL PROCEDURAL GENERATOR FOR ALL 20 CAREER FIELDS
// =========================================================================
function generateProceduralBank(domain, roleName, fieldName, diffLevel, userSkillsStr, askedQuestions = [], isRegen = false) {
  // Check if we have dedicated pre-compiled questions for this domain
  const pool = DOMAIN_QUESTION_POOLS[domain] || DOMAIN_QUESTION_POOLS["software"];
  if (pool) {
    const filterUnused = (list) => {
      const unused = list.filter((item) => !isDuplicate(item.q, askedQuestions));
      return unused.length >= 8 ? unused : list; // Fallback to list if all used
    };

    const techList = filterUnused(pool.technical);
    const probList = filterUnused(pool.problemSolving);
    const behList = filterUnused(pool.behavioral);
    const sitList = filterUnused(pool.situational);
    const roleList = filterUnused(pool.roleSpecific);

    // Format into standard categories
    return {
      role: roleName,
      difficulty: diffLevel,
      careerField: fieldName,
      totalQuestions: techList.length + probList.length + behList.length + sitList.length + roleList.length,
      categories: [
        {
          name: "Technical & Core Principles",
          description: `Core technical, theoretical, and domain-specific questions for ${roleName}`,
          questions: techList.map((item) => ({
            question: item.q,
            difficulty: item.diff,
            keyConcepts: item.concepts,
            modelAnswer: item.ans,
          })),
        },
        {
          name: "Problem-Solving & System Design",
          description: `Practical troubleshooting, architectural design, and calculation challenges for ${roleName}`,
          questions: probList.map((item) => ({
            question: item.q,
            difficulty: item.diff,
            keyConcepts: item.concepts,
            modelAnswer: item.ans,
          })),
        },
        {
          name: "Behavioral Questions (STAR Method)",
          description: `Evaluating leadership, accountability, and teamwork in ${roleName} environments`,
          questions: behList.map((item) => ({
            question: item.q,
            difficulty: item.diff,
            keyConcepts: item.concepts,
            modelAnswer: item.ans,
          })),
        },
        {
          name: "Situational & Crisis Management",
          description: `Real-world workplace scenarios, emergency response, and operational decision-making`,
          questions: sitList.map((item) => ({
            question: item.q,
            difficulty: item.diff,
            keyConcepts: item.concepts,
            modelAnswer: item.ans,
          })),
        },
        {
          name: "Role-Specific Tools & Industry Standards",
          description: `Governing standards, software workflows, and specialized best practices for ${roleName}`,
          questions: roleList.map((item) => ({
            question: item.q,
            difficulty: item.diff,
            keyConcepts: item.concepts,
            modelAnswer: item.ans,
          })),
        },
      ],
    };
  }
}

// =========================================================================
// 3. MAIN EXPORTED FUNCTION: GENERATE OR REGENERATE PRACTICE QUESTION BANK
// =========================================================================
async function generatePracticeQuestionBank(params) {
  const {
    careerField = "",
    role = "Engineering Professional",
    difficulty = "Intermediate",
    skills = "",
    education = "",
    experience = "",
    projects = "",
    certifications = "",
    candidateName = "",
    jobDescription = "",
    isRegenerate = false,
    askedQuestions = [],
  } = params;

  const targetRoleName = role ? role.trim() : "Engineering Professional";
  const fieldName = careerField ? careerField.trim() : "";
  const diffLevel = difficulty || "Intermediate";
  const userSkillsStr = skills ? skills.trim() : "Domain Engineering";

  console.log(`[PRACTICE_BANK] Generating question bank for Role: "${targetRoleName}", Field: "${fieldName}", Diff: "${diffLevel}", isRegen: ${isRegenerate}`);
  console.log(`[PRACTICE_BANK] Exclusion list size: ${Array.isArray(askedQuestions) ? askedQuestions.length : 0}`);

  // Detect domain using multi-disciplinary detector
  const combined = `${fieldName} ${targetRoleName} ${userSkillsStr}`.toLowerCase();
  let domain = "software";
  if (/cyber|information\s*sec|infosec|soc\b|penetration|ethical\s*hack|vulnerab|wireshark|siem/i.test(combined)) {
    domain = "cybersecurity";
  } else if (/mechanic|autocad|solidworks|catia|ansys|fea|cad\b|gdt|hvac|thermodynamics|machine\s*design/i.test(combined)) {
    domain = "mechanical";
  }

  const proceduralBank = generateProceduralBank(
    domain,
    targetRoleName,
    fieldName,
    diffLevel,
    userSkillsStr,
    askedQuestions,
    isRegenerate
  );

  console.log(`[PRACTICE_BANK] Procedural bank generated with ${proceduralBank.totalQuestions} questions across ${proceduralBank.categories.length} categories.`);
  return proceduralBank;
}

module.exports = {
  generatePracticeQuestionBank,
  isDuplicate,
  normalizeQ,
};
